import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CustomButton from "../stories/CustomButton";
import { Button } from "../stories/Button";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>StoryBoook Demo:</h1>

      <CustomButton
        backgroundColor="#d97474"
        color="#6f6060"
        handleClick={() => {
          alert("hello");
        }}
        label="Press Me"
        size="lg"
      />
    </div>
  );
}
